import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {applyJourney,emptyJourney,clientJourney} from '../../packages/journey/model';
import {attribution} from '../../packages/journey/attribution';
import {testDatabase} from './database';
import {migrate} from '../src/migrate';
import {createApp} from '../src/app';
import {readConfig} from '../src/config';
import {hashPassword} from '../src/security';
import {upsertCatalogProperty} from '../src/catalogRepository';
import {DEFAULT_STATE} from '../../packages/pulse-data/model';
test('Путь клиента: черновики, реакция, переходы и сроки',()=>{
 const now=new Date('2026-09-27T00:00:00Z'),id=randomUUID();let j=emptyJourney(id);
 const collection={type:'collection' as const,id:randomUUID(),title:'Подборка',items:[{propertyId:'primorskiy',note:'Подходит по району'}],published:false};
 j=applyJourney(j,collection,'manager',now);assert.equal(clientJourney(j).collections.length,0);
 assert.throws(()=>applyJourney(j,{type:'reaction',collectionId:collection.id,propertyId:'primorskiy',reaction:'liked',reply:''},'client',now));
 j=applyJourney(j,{...collection,published:true},'manager',now);
 j=applyJourney(j,{type:'reaction',collectionId:collection.id,propertyId:'primorskiy',reaction:'expensive',reply:'Уточним бюджет'},'client',now);
 assert.equal(j.collections[0].items[0].reaction,'expensive');
 assert.throws(()=>applyJourney(j,{type:'next_step',title:'Позвонить',dueAt:now.toISOString(),done:false},'client',now));
 const show={type:'showing' as const,id:randomUUID(),propertyId:'primorskiy',at:'2026-09-28T00:00:00Z',note:''};
 j=applyJourney(j,show,'client',now);assert.throws(()=>applyJourney(j,{...show,id:randomUUID()},'client',now));
 assert.throws(()=>applyJourney(j,{type:'showing_status',id:show.id,status:'completed',result:'Понравилось'},'manager',now));
 j=applyJourney(j,{type:'showing_status',id:show.id,status:'confirmed',result:''},'manager',now);
 assert.throws(()=>applyJourney(j,{type:'showing_status',id:show.id,status:'completed',result:''},'manager',now));
 j=applyJourney(j,{type:'showing_status',id:show.id,status:'completed',result:'Обсудить альтернативу'},'manager',now);
 assert.equal(clientJourney(j).showings[0].result,'');
 assert.deepEqual(attribution('?utm_source=telegram&utm_campaign=autumn'),{source:'telegram',medium:'',campaign:'autumn'});
});
test('Journey API: доступ, конфликт версий, публикация, показы, аналитика и проверки каталога',async t=>{
 const db=await testDatabase();await migrate(db);const config=readConfig({NODE_ENV:'test',DATABASE_URL:'unused',PUBLIC_ORIGIN:'http://localhost:8080'});const app=await createApp(db,config);await app.ready();t.after(async()=>{await app.close();await db.close()});
 const manager=(await db.query("insert into team_members(name,email,password_hash,role) values('Owner','owner@test.local',$1,'owner') returning id",[await hashPassword('long-test-password')])).rows[0];
 const other=(await db.query("insert into team_members(name,email,password_hash,role) values('Other','other@test.local',$1,'manager') returning id",[await hashPassword('long-test-password')])).rows[0];
 const headers={'content-type':'application/json',origin:config.PUBLIC_ORIGIN};
 const login=async(email:string)=>(await app.inject({method:'POST',url:'/api/v1/control/login',headers,payload:{email,password:'long-test-password'}})).cookies[0].value;
 const cookies={pulse_control:await login('owner@test.local')},otherCookies={pulse_control:await login('other@test.local')};
 for(const p of DEFAULT_STATE.properties)await db.transaction(sql=>upsertCatalogProperty(sql,p));
 const session=async(source='direct')=>(await app.inject({method:'POST',url:'/api/v1/auth/session',headers,payload:{source,campaign:'autumn'}})).json();
 const a=await session('telegram'),b=await session();const auth={...headers,authorization:'Bearer '+a.accessToken},unauthorized={...headers,authorization:'Bearer '+b.accessToken};
 const lead=(await app.inject({method:'POST',url:'/api/v1/leads',headers:auth,payload:{idempotencyKey:randomUUID(),source:'property',propertyId:'primorskiy',name:'Тест',phone:'+79990000001',consent:true,consentVersion:config.CONSENT_VERSION}})).json();
 assert.ok(lead.id);await db.query('update leads set manager_id=$2 where id=$1',[lead.id,manager.id]);
 const path='/api/v1/control/journeys/'+lead.id,clientPath='/api/v1/me/journeys/'+lead.id;
 const collection={type:'collection',id:randomUUID(),title:'Два варианта',items:[{propertyId:'primorskiy',note:'Центр'},{propertyId:'solnechniy',note:'У моря'}],published:false};
 const post=(url:string,command:any,revision:number,client=false)=>app.inject({method:'POST',url,headers:client?auth:headers,cookies:client?undefined:cookies,payload:{revision,command}});
 assert.equal((await app.inject('/api/v1/control/journeys')).statusCode,401);
 assert.equal((await app.inject({method:'POST',url:path,headers,cookies:otherCookies,payload:{revision:0,command:collection}})).statusCode,404);
 let response=await post(path,collection,0);assert.equal(response.statusCode,200,response.body);
 const mine=async()=>(await app.inject({url:'/api/v1/me/journeys',headers:auth})).json().items.find((x:any)=>x.leadId===lead.id).journey;
 assert.equal((await mine()).collections.length,0);
 assert.equal((await app.inject({url:'/api/v1/me/journeys',headers:unauthorized})).json().items.length,0);
 assert.equal((await post(path,collection,0)).statusCode,409);
 response=await post(path,{...collection,published:true},1);assert.equal(response.statusCode,200,response.body);assert.equal((await mine()).collections.length,1);
 const reaction={type:'reaction',collectionId:collection.id,propertyId:'primorskiy',reaction:'liked',reply:'Хочу посмотреть'};
 assert.equal((await post(path,reaction,2)).statusCode,400);
 response=await post(clientPath,reaction,2,true);assert.equal(response.statusCode,200,response.body);
 assert.equal((await db.query("select * from user_events where event_type='collection_reaction'")).rows.length,1);
 assert.equal((await app.inject({method:'POST',url:clientPath,headers:unauthorized,payload:{revision:3,command:reaction}})).statusCode,404);
 const show={type:'showing',id:randomUUID(),propertyId:'primorskiy',at:new Date(Date.now()+86400000).toISOString(),note:'После работы'};
 response=await post(clientPath,show,3,true);assert.equal(response.statusCode,200,response.body);
 response=await post(path,{type:'showing_status',id:show.id,status:'confirmed',result:''},4);assert.equal(response.statusCode,200,response.body);
 const secondLead=(await app.inject({method:'POST',url:'/api/v1/leads',headers:auth,payload:{idempotencyKey:randomUUID(),source:'property',propertyId:'solnechniy',name:'Другой тест',phone:'+79990000002',consent:true,consentVersion:config.CONSENT_VERSION}})).json();
 await db.query('update leads set manager_id=$2 where id=$1',[secondLead.id,manager.id]);
 const secondPath='/api/v1/control/journeys/'+secondLead.id;const secondShow={...show,id:randomUUID(),propertyId:'solnechniy'};
 assert.equal((await post(secondPath,secondShow,0)).statusCode,200);
 assert.equal((await post(secondPath,{type:'showing_status',id:secondShow.id,status:'confirmed',result:''},1)).statusCode,409);
 response=await post(path,{type:'showing_status',id:show.id,status:'completed',result:'Клиент выбирает этаж'},5);assert.equal(response.statusCode,200,response.body);
 assert.equal((await mine()).showings[0].result,'');
 const messageId=randomUUID();response=await post(path,{type:'message',id:messageId,text:'Документы по квартире',attachment:{kind:'file',name:'offer.pdf',url:'/media/chat/test.pdf',mimeType:'application/pdf',size:1024}},6);assert.equal(response.statusCode,200,response.body);
 let clientJourneyState=await mine();assert.equal(clientJourneyState.messages[0].attachment.name,'offer.pdf');assert.equal(clientJourneyState.messages[0].readAt,undefined);
 response=await app.inject({method:'POST',url:clientPath+'/read',headers:auth,payload:{messageIds:[messageId]}});assert.equal(response.statusCode,200,response.body);assert.ok(response.json().journey.messages[0].readAt);
 const managerJourney=(await app.inject({url:'/api/v1/control/journeys',cookies})).json().items.find((x:any)=>x.leadId===lead.id).journey;assert.ok(managerJourney.messages[0].readAt);
 const acquisition=await app.inject({url:'/api/v1/control/acquisition',cookies});assert.equal(acquisition.statusCode,200,acquisition.body);const row=acquisition.json().items.find((r:any)=>r.source==='telegram');assert.equal(row.contacts,1);assert.equal(row.showings,1);
 const verify=()=>app.inject({method:'POST',url:'/api/v1/control/verifications/primorskiy',headers,cookies,payload:{note:'Сверено с застройщиком',revision:0}});
 response=await verify();assert.equal(response.statusCode,200,response.body);assert.equal((await verify()).statusCode,409);
 assert.equal((await app.inject('/api/v1/public/verifications')).json().items.length,1);
 assert.equal((await app.inject({method:'POST',url:'/api/v1/control/verifications/primorskiy',headers,cookies:otherCookies,payload:{note:'',revision:1}})).statusCode,403);
 response=await app.inject({method:'POST',url:'/api/v1/control/verifications/primorskiy',headers,cookies,payload:{note:'Повторная проверка',revision:1}});assert.equal(response.statusCode,200,response.body);
 await db.query("update leads set status='closed' where id=$1",[lead.id]);assert.equal((await post(path,{...collection,published:false},6)).statusCode,409);
});
