import React from 'react';
import {ShowingChange} from './ShowingChange';
import {loadJourneys,saveJourney,type JourneyEntry} from './client';
import {reactionLabels,showingLabels,emptyJourney,type Journey,type JourneyCommand,type Reaction} from './model';
import type {PulseProperty} from '../pulse-data/model';
import './journey.css';
const when=(v:string)=>new Date(v).toLocaleString('ru-RU',{timeZone:'Asia/Vladivostok',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'});
const iso=(v:string)=>new Date(v+'+10:00').toISOString();
export function JourneyPanel({leadId,properties,client=false,onRefreshed}:{leadId?:string;properties:PulseProperty[];client?:boolean;onRefreshed?:(items:JourneyEntry[])=>void}){
 const [entries,setEntries]=React.useState<JourneyEntry[]>([]),[error,setError]=React.useState(''),[loading,setLoading]=React.useState(true),[busy,setBusy]=React.useState(false);
 const [picked,setPicked]=React.useState<string[]>([]),[title,setTitle]=React.useState('Варианты для вас'),[notes,setNotes]=React.useState<Record<string,string>>({});
 const [step,setStep]=React.useState(''),[due,setDue]=React.useState(''),[time,setTime]=React.useState(''),[propertyId,setPropertyId]=React.useState(''),[note,setNote]=React.useState('');
 const [message,setMessage]=React.useState<Record<string,string>>({});
 const [replies,setReplies]=React.useState<Record<string,string>>({}),[results,setResults]=React.useState<Record<string,string>>({});
 const reload=React.useCallback(async()=>{setLoading(true);try{const data=await loadJourneys(client);setEntries(data.items);onRefreshed?.(data.items);setError(data.limited?'Показаны последние 1000 обращений':'');}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[client,leadId,onRefreshed]);
 React.useEffect(()=>{void reload();const refresh=()=>{if(!document.hidden)void reload()};window.addEventListener('focus',refresh);window.addEventListener('online',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);document.removeEventListener('visibilitychange',refresh)}},[reload]);
 const run=async(j:Journey,c:JourneyCommand)=>{setBusy(true);setError('');try{await saveJourney(j,c,client);if(c.type==='collection'){setPicked([]);setNotes({})}await reload();if(c.type==='message')setMessage(v=>({...v,[j.leadId]:''}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const list=leadId?entries.filter(e=>e.leadId===leadId):entries;
 const name=(id:string)=>properties.find(p=>p.id===id)?.name||'Объект недоступен';
 return <section className="pulseJourney" aria-label={client?'Мои подборки и показы':'Подборки и показы'}><header><div><small>СОПРОВОЖДЕНИЕ ПОКУПКИ</small><h2>{client?'Мои подборки и показы':'Подборки и показы'}</h2></div><button disabled={busy||loading} onClick={()=>void reload()}>Обновить</button></header>
 {error&&<p role="alert">{error}</p>}{loading&&<p role="status">Загружаем обращения…</p>}{!loading&&!list.length&&<p>После обращения в агентство здесь появятся подборки и встречи с менеджером.</p>}
 {list.map(entry=>{const j=entry.journey||emptyJourney(entry.leadId);const closed=['deal','closed','lost'].includes(entry.status);const options=client?properties.filter(p=>p.id===entry.propertyId||j.collections.some(c=>c.items.some(i=>i.propertyId===p.id))):properties.filter(p=>p.status==='published');return <article key={entry.leadId} className="journeyLead" id={"lead-"+entry.leadId}><p><b>Обращение от {when(entry.createdAt)}</b> · {({new:'Принято',contacted:'Менеджер связался',qualified:'Подбираем варианты',showing:'Организуем показ',booking:'Бронирование',deal:'Сделка завершена',closed:'Завершено',lost:'Закрыто'} as Record<string,string>)[entry.status]||entry.status}</p>
 {client&&<p>{entry.managerName?'Ваш менеджер: '+entry.managerName:'Ответственный менеджер ещё не назначен. Команда увидит ваше обращение.'}</p>}
 <details className="journeyMessages"><summary>Переписка по обращению{j.messages?.length?' · '+j.messages.length:''}</summary>{!j.messages?.length&&<p>Здесь можно задать вопрос по подборке или показу. Ответ появится в обращении; при подключённом боте придёт уведомление в Telegram.</p>}{j.messages?.map(m=><div className="journeyItem" key={m.id}><b>{m.author==='manager'?'Менеджер':'Клиент'}</b><small> · {when(m.at)}</small><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p></div>)}{!closed&&<><label>Сообщение<textarea maxLength={2000} value={message[entry.leadId]||''} onChange={e=>setMessage({...message,[entry.leadId]:e.target.value})}/></label><button disabled={busy||!message[entry.leadId]?.trim()} onClick={()=>void run(j,{type:'message',id:crypto.randomUUID(),text:message[entry.leadId]})}>Отправить сообщение</button></>}</details>
 {j.collections.map(c=><section className="journeyCollection" key={c.id}><h3>{c.title} {!c.published&&<small>Черновик</small>}</h3>{c.items.map(i=><div className="journeyItem" key={i.propertyId}><a href={(client?'#/property/':'../mini-app/#/property/')+encodeURIComponent(i.propertyId)}>{name(i.propertyId)}</a><p>{i.note}</p>{client?<><label>Ваше мнение<select disabled={busy||closed} value={i.reaction} onChange={e=>void run(j,{type:'reaction',collectionId:c.id,propertyId:i.propertyId,reaction:e.target.value as Reaction,reply:i.reply})}>{Object.entries(reactionLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Комментарий к варианту<textarea maxLength={2000} value={replies[c.id+i.propertyId]??i.reply} onChange={e=>setReplies({...replies,[c.id+i.propertyId]:e.target.value})}/></label><button disabled={busy||closed} onClick={()=>void run(j,{type:'reaction',collectionId:c.id,propertyId:i.propertyId,reaction:i.reaction,reply:replies[c.id+i.propertyId]??i.reply})}>Сохранить ответ</button></>:<p><b>{reactionLabels[i.reaction]}</b>{i.reply&&' · '+i.reply}</p>}</div>)}{!client&&!closed&&<button disabled={busy} onClick={()=>void run(j,{type:'collection',id:c.id,title:c.title,items:c.items,published:!c.published})}>{c.published?'Снять с публикации':'Опубликовать клиенту'}</button>}</section>)}
 {!client&&!closed&&<details><summary>Создать подборку</summary><label>Название<input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><div className="journeyPicker">{options.map(p=><div key={p.id}><label><input type="checkbox" checked={picked.includes(p.id)} disabled={!picked.includes(p.id)&&picked.length>=10} onChange={e=>setPicked(e.target.checked?[...picked,p.id]:picked.filter(id=>id!==p.id))}/>{p.name}</label>{picked.includes(p.id)&&<input aria-label={'Почему подходит '+p.name} placeholder="Почему этот вариант подходит" maxLength={2000} value={notes[p.id]||''} onChange={e=>setNotes({...notes,[p.id]:e.target.value})}/>}</div>)}</div><button disabled={busy||!picked.length||!title.trim()} onClick={()=>void run(j,{type:'collection',id:crypto.randomUUID(),title,items:picked.map(propertyId=>({propertyId,note:notes[propertyId]||''})),published:false})}>Сохранить черновик</button></details>}
 <h3>Показы</h3><small>Время Владивостока (UTC+10). Запрос времени подтверждает менеджер.</small>{!j.showings.length&&<p>Пока нет запланированных показов.</p>}{j.showings.map(s=><div className="journeyItem" key={s.id}><b>{name(s.propertyId)}</b><p>{when(s.at)} · {showingLabels[s.status]}</p><p>{s.note}</p><ShowingChange showing={s} client={client} closed={closed} busy={busy} onCommand={c=>run(j,c)}/>{!client&&<><p>{s.result}</p>{!closed&&['requested','confirmed'].includes(s.status)&&<><label>Результат / причина<textarea maxLength={2000} value={results[s.id]||''} onChange={e=>setResults({...results,[s.id]:e.target.value})}/></label><div className="journeyActions">{(s.status==='requested'?['confirmed','cancelled']:['completed','cancelled']).map(status=><button disabled={busy} key={status} onClick={()=>void run(j,{type:'showing_status',id:s.id,status:status as any,result:results[s.id]||''})}>{showingLabels[status as keyof typeof showingLabels]}</button>)}</div></>}</>}</div>)}
 {!closed&&<details><summary>Запросить время показа</summary><label>ЖК<select aria-label="ЖК" value={propertyId} onChange={e=>setPropertyId(e.target.value)}><option value="">Выберите объект</option>{options.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Дата и время (Владивосток)<input type="datetime-local" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Пожелания<input maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy||!time||!propertyId} onClick={()=>void run(j,{type:'showing',id:crypto.randomUUID(),propertyId,at:iso(time),note})}>Запросить показ</button></details>}
 {!client&&<><h3>Следующий шаг</h3>{j.nextStep&&<p><b>{j.nextStep.title}</b> · {when(j.nextStep.dueAt)} · {j.nextStep.done?'Выполнен':Date.parse(j.nextStep.dueAt)<Date.now()?'Просрочен':'Запланирован'} {!j.nextStep.done&&<button disabled={busy||closed} onClick={()=>void run(j,{type:'next_step',...j.nextStep!,done:true})}>Завершить</button>}</p>}{!closed&&<details><summary>Запланировать действие</summary><label>Что сделать<input value={step} maxLength={200} onChange={e=>setStep(e.target.value)}/></label><label>Срок (Владивосток)<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><button disabled={busy||!step.trim()||!due} onClick={()=>void run(j,{type:'next_step',title:step,dueAt:iso(due),done:false})}>Сохранить следующий шаг</button></details>}</>}
 </article>})}</section>;
}
