import React from 'react';
import type {Showing,JourneyCommand} from './model';
import {isFutureVladivostokInput,vladivostokInputNow,vladivostokInputToIso} from './time';
const when=(v:string)=>new Date(v).toLocaleString('ru-RU',{timeZone:'Asia/Vladivostok'});
export function ShowingChange({showing:s,client,closed,busy,onCommand}:{showing:Showing;client:boolean;closed:boolean;busy:boolean;onCommand:(c:JourneyCommand)=>Promise<void>}){
 const [at,setAt]=React.useState(''),[note,setNote]=React.useState('');
 const validAt=!at||isFutureVladivostokInput(at);
 const minDateTime=vladivostokInputNow();
 return <>{s.proposedAt&&<p>Запрошен перенос на {when(s.proposedAt)}. До подтверждения действует прежнее время. {s.changeNote}</p>}{s.changeDecision&&<p>{s.changeDecision==='accepted'?'Перенос подтверждён.':'Менеджер отклонил перенос. Обсудите другое время в переписке.'}</p>}{s.status==='cancelled'&&s.changeNote&&<p>Причина отмены: {s.changeNote}</p>}{!closed&&['requested','confirmed'].includes(s.status)&&(client?<details><summary>Изменить или отменить показ</summary><label>Новое время (Владивосток)<input type="datetime-local" aria-label="Новое время (Владивосток)" min={minDateTime} value={at} onChange={e=>setAt(e.target.value)}/>{at&&!validAt&&<small className="journeyFieldError">Выберите будущее время.</small>}</label><label>Комментарий<input value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><div className="journeyActions"><button disabled={busy||!at||!validAt} onClick={()=>{const value=vladivostokInputToIso(at);if(value)void onCommand({type:'showing_change',id:s.id,action:'reschedule',at:value,note})}}>Запросить перенос</button><button disabled={busy} onClick={()=>void onCommand({type:'showing_change',id:s.id,action:'cancel',note})}>Отменить показ</button></div></details>:s.proposedAt&&<div className="journeyActions"><button disabled={busy} onClick={()=>void onCommand({type:'showing_reschedule',id:s.id,accept:true})}>Подтвердить перенос</button><button disabled={busy} onClick={()=>void onCommand({type:'showing_reschedule',id:s.id,accept:false})}>Отклонить перенос</button></div>)}</>;
}
