import React from 'react';
import {Link} from 'react-router-dom';
import {PageFrame} from '../components/PageFrame';
import {usePulseLeads,usePulseState} from '../data';
import {loadJourneys,loadVerifications,verifyProperty,type JourneyEntry} from '../../../../packages/journey/client';
import {staleVerification,showingLabels,type Verification} from '../../../../packages/journey/model';
import {runtime} from '../../../../packages/pulse-data/runtime';
import '../../../../packages/journey/journey.css';
export function JourneyPage(){
 const leads=usePulseLeads(),state=usePulseState();const [items,setItems]=React.useState<JourneyEntry[]>([]),[checks,setChecks]=React.useState<Verification[]>([]),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[notes,setNotes]=React.useState<Record<string,string>>({}),[day,setDay]=React.useState('');
 const reload=async()=>{try{const [j,v]=await Promise.all([loadJourneys(),loadVerifications()]);setItems(j.items);setChecks(v);setError(j.limited?'Показаны последние 1000 обращений':'')}catch(e){setError((e as Error).message)}};
 React.useEffect(()=>{void reload()},[]);
 const active=leads.filter(l=>!['deal','closed','lost'].includes(l.status));
 const missing=active.filter(l=>{const n=items.find(i=>i.leadId===l.id)?.journey.nextStep;return !n||n.done});
 const upcoming=items.flatMap(e=>e.journey.showings.map(s=>({...s,leadId:e.leadId}))).filter(s=>!day||new Date(s.at).toLocaleDateString('en-CA',{timeZone:'Asia/Vladivostok'})===day).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));
 const name=(id:string)=>leads.find(l=>l.id===id)?.name||'Клиент';
 const check=async(id:string)=>{setBusy(true);setError('');try{await verifyProperty(id,notes[id]||'',checks.find(v=>v.propertyId===id)?.revision||0);await reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <PageFrame eyebrow="ОТ ПОДБОРА ДО ПОКАЗА" title="Сопровождение клиентов" description="Персональные подборки открываются в карточке лида. Здесь — встречи, обязательства и актуальность каталога."><section className="pulseJourney"><header><h2>Рабочая очередь</h2><button disabled={busy} onClick={()=>void reload()}>Обновить</button></header>{error&&<p role="alert">{error}</p>}<h3>Без запланированного следующего шага · {missing.length}</h3>{missing.map(l=><p key={l.id}><Link to={'/leads?lead='+l.id}>{l.name}</Link> · {l.status==='new'?'Новое обращение':'Нужен следующий шаг'}</p>)}{items.filter(e=>!['deal','closed','lost'].includes(e.status)&&e.journey.nextStep&&!e.journey.nextStep.done).sort((a,b)=>Date.parse(a.journey.nextStep!.dueAt)-Date.parse(b.journey.nextStep!.dueAt)).map(e=><p key={e.leadId}><Link to={'/leads?lead='+e.leadId}>{name(e.leadId)}</Link> · {e.journey.nextStep!.title} · {new Date(e.journey.nextStep!.dueAt).toLocaleString('ru-RU',{timeZone:'Asia/Vladivostok'})} {Date.parse(e.journey.nextStep!.dueAt)<Date.now()&&<b>Просрочено</b>}</p>)}</section>
 <section className="pulseJourney"><h2>Календарь показов</h2><label>День по Владивостоку<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><button onClick={()=>setDay('')}>Все даты</button>{!upcoming.length&&<p>Показов на выбранную дату нет.</p>}{upcoming.map(s=><article className="journeyItem" key={s.id}><Link to={'/leads?lead='+s.leadId}>{name(s.leadId)}</Link><p>{state.properties.find(p=>p.id===s.propertyId)?.name||'Объект из истории'} · {new Date(s.at).toLocaleString('ru-RU',{timeZone:'Asia/Vladivostok'})} · {showingLabels[s.status]}</p><p>{s.result}</p></article>)}</section>
 {(!runtime.enabled||runtime.member?.role!=='manager')&&<section className="pulseJourney"><h2>Актуальность объектов</h2><p>Проверка нужна каждые 7 дней. Подтверждайте после сверки цены и наличия с застройщиком. Комментарий увидит клиент.</p>{state.properties.filter(p=>p.status==='published').sort((a,b)=>Number(staleVerification(checks.find(v=>v.propertyId===b.id)))-Number(staleVerification(checks.find(v=>v.propertyId===a.id)))).map(p=>{const v=checks.find(v=>v.propertyId===p.id);const missing=[!p.coverImageUrl&&'обложка',!p.floorplans.length&&'планировки',!p.documents?.length&&'документы',p.latitude==null&&'координаты'].filter(Boolean);return <details key={p.id}><summary>{p.name} · {staleVerification(v)?'Требует проверки':'Проверен'}</summary><p>{v?'Проверено '+new Date(v.checkedAt).toLocaleDateString('ru-RU'):'Пока не проверялся'}{missing.length?' · Не хватает: '+missing.join(', '):''}</p><label>Уточнение для клиента<input maxLength={2000} value={notes[p.id]??v?.note??''} onChange={e=>setNotes({...notes,[p.id]:e.target.value})}/></label><button disabled={busy} onClick={()=>void check(p.id)}>Цена и наличие проверены</button></details>})}</section>}
 </PageFrame>;
}
