import { ControlJourneyPanel } from '../../../../packages/journey/ControlJourneyPanel';
import { useDialog } from "../components/useDialog";
import React from 'react';
import { useSearchParams } from 'react-router-dom';
import { InterestPanel } from '../components/InterestPanel';
import { Search, Phone, X, Save, Gauge } from 'lucide-react';
import { PageFrame } from '../components/PageFrame';
import { usePulseLeads, usePulseState, usePulseEvents, usePulseTasks } from '../data';
import { leadSourceName, priorityName, taskStatusName } from '../activityCopy';
import { updatePulseLead, type PulseLead } from '../../../../packages/pulse-data';
import { runtime, updateRemote } from '../../../../packages/pulse-data/runtime';
import { cleanManagerComment, describeLeadRequestContext, leadRequestContext } from '../../../../packages/pulse-data/leadContext';
const statuses:PulseLead['status'][]=['new','contacted','qualified','showing','booking','deal','closed','lost'];
const labels:Record<PulseLead['status'],string>={new:'Новый',contacted:'Связались',qualified:'Квалифицирован',showing:'Показ',booking:'Бронь',deal:'Сделка',closed:'Закрыт',lost:'Потерян'};
type LeadDraft={status:PulseLead['status'];manager:string|null;comment:string;nextAction:string;expectedUpdatedAt:string};
const makeDraft=(lead:PulseLead):LeadDraft=>({status:lead.status,manager:lead.manager,comment:cleanManagerComment(lead.comment),nextAction:lead.nextAction||'',expectedUpdatedAt:lead.updatedAt});
const draftValues=(draft:LeadDraft)=>({status:draft.status,manager:draft.manager,comment:draft.comment,nextAction:draft.nextAction});
export function LeadsPage(){
 const leads=usePulseLeads();const state=usePulseState();const events=usePulseEvents();const tasks=usePulseTasks();
 const [params,setParams]=useSearchParams();
 const [mode,setMode]=React.useState('active');const [query,setQuery]=React.useState('');const [selected,setSelected]=React.useState<string|null>(new URLSearchParams(location.hash.split('?')[1]).get('lead'));
 const [draft,setDraft]=React.useState<LeadDraft|null>(null);const [busy,setBusy]=React.useState(false);const [error,setError]=React.useState('');
 const baseline=React.useRef<ReturnType<typeof draftValues>|null>(null);
 const lead=leads.find(x=>x.id===selected);
 const open=(item:PulseLead)=>{const next=makeDraft(item);baseline.current=draftValues(next);setSelected(item.id);setDraft(next);setError('');};
 React.useEffect(()=>{if(!selected){setDraft(null);baseline.current=null;return}if(!draft&&lead)open(lead)},[selected,lead?.id]);
 React.useEffect(()=>{const id=params.get('lead');if(!id)return;const item=leads.find(l=>l.id===id);if(item&&selected!==id)open(item)},[params.get('lead'),leads.length]);
 const dirty=!!draft&&!!baseline.current&&JSON.stringify(draftValues(draft))!==JSON.stringify(baseline.current);
 const stage=params.get('status');const unassigned=params.get('filter')==='unassigned';const board=params.get('view')==='board';
 const visible=leads.filter(l=>(!stage||l.status===stage)&&(!unassigned||!l.manager)&&(!!stage||mode==='all'||mode==='hot'&&['hot','urgent'].includes(l.priority||'')||mode==='active'&&!['closed','lost','deal'].includes(l.status))&&(l.name+' '+l.phone+' '+leadSourceName(l.source)+' '+(state.properties.find(p=>p.id===(l.topPropertyId||l.propertyId))?.name||'')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.score||0)-(a.score||0)||Date.parse(b.createdAt)-Date.parse(a.createdAt));
 const close=()=>{if(busy)return;if(dirty&&!window.confirm('Закрыть карточку без сохранения правок?'))return;setSelected(null);setDraft(null);baseline.current=null;const p=new URLSearchParams(params);p.delete('lead');setParams(p)};
 useDialog(!!lead&&!!draft,close);
 const save=async()=>{if(!lead||!draft)return;if(!dirty){close();return}setBusy(true);setError('');try{const patch:Record<string,unknown>={status:draft.status,comment:draft.comment||null,nextAction:draft.nextAction||null,expectedUpdatedAt:draft.expectedUpdatedAt};if(!runtime.enabled||runtime.member?.role!=='manager')patch.manager=draft.manager;if(runtime.enabled)await updateRemote('leads',lead.id,patch);else updatePulseLead(lead.id,patch);baseline.current=draftValues(draft);setSelected(null);setDraft(null);const p=new URLSearchParams(params);p.delete('lead');setParams(p);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}};
 const requestContext=lead?leadRequestContext(lead.requestContext,lead.comment):{};
 const requestSummary=lead?describeLeadRequestContext(requestContext,lead.source):{title:'Контекст обращения',lines:[] as string[]};
 return <PageFrame eyebrow="КЛИЕНТЫ" title="Лиды" description="Контекст клиента, ответственный и следующий шаг — в одной карточке.">
  <div className="toolbar"><div className="segmented">{[['active','В работе'],['hot','Горячие'],['all','Все']].map(([value,label])=><button key={value} className={mode===value?'active':''} onClick={()=>{setMode(value);if(stage){const p=new URLSearchParams(params);p.delete("status");setParams(p)}}}>{label}</button>)}</div><label className="controlSearch"><Search size={17}/><input aria-label="Поиск клиента" placeholder="Имя, телефон, ЖК или источник" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
  <div className="leadsViewBar"><span>{visible.length} клиентов{stage?' · '+labels[stage as PulseLead['status']]:''}{unassigned?' · Без ответственного':''}</span><div className="filterChips">{(stage||unassigned)&&<button onClick={()=>setParams({})}>Сбросить фильтры</button>}<button aria-pressed={!board} onClick={()=>{const p=new URLSearchParams(params);p.delete('view');setParams(p)}}>Таблица</button><button aria-pressed={board} onClick={()=>setParams({...Object.fromEntries(params),view:'board'})}>Доска</button></div></div>
  {board?<section className="leadBoard">{statuses.filter(s=>!['closed','lost'].includes(s)||mode==='all').map(status=><div className="kanbanCol" key={status}><div className="kanbanTitle"><b>{labels[status]}</b><span>{visible.filter(l=>l.status===status).length}</span></div>{visible.filter(l=>l.status===status).map(l=><button className="leadBoardCard" key={l.id} onClick={()=>open(l)}><span className={'scoreBadge '+(l.priority||'cold')}><b>{l.score||0}</b>{priorityName(l.priority)}</span><b>{l.name}</b><small>{state.properties.find(p=>p.id===(l.topPropertyId||l.propertyId))?.name||leadSourceName(l.source)}</small><p>{l.nextAction||'Связаться и уточнить задачу'}</p><span>{runtime.snapshot.members.find(m=>m.id===l.manager)?.name||l.manager||'Не назначен'}</span></button>)}</div>)}</section>:<section className="tableCard liveTable"><div className="tableHead leadsScoreGrid"><span>Клиент</span><span>Интерес</span><span>Статус</span><span>Менеджер</span><span>Следующее действие</span></div>
   {!visible.length?<div className="emptyState"><strong>Заявок не найдено</strong><span>Новые обращения появятся здесь после отправки из мини‑аппа.</span></div>:visible.map(l=><button className="tableRow leadsScoreGrid leadRowButton" onClick={()=>open(l)} key={l.id}><span className="leadName"><b>{l.name}</b><small>{l.phone}</small><small>{leadSourceName(l.source)}</small></span><span className="scoreCell"><span className={'scoreBadge '+(l.priority||'cold')}><Gauge size={14}/><b>{l.score||0}</b><small>{priorityName(l.priority)}</small></span><small>{state.properties.find(p=>p.id===(l.topPropertyId||l.propertyId))?.name||'Общий подбор'}</small></span><span className="statusChip">{labels[l.status]}</span><span>{runtime.snapshot.members.find(m=>m.id===l.manager)?.name||l.manager||'Не назначен'}</span><span className="nextAction"><b>{l.nextAction||'Связаться и уточнить задачу'}</b><small>{new Date(l.createdAt).toLocaleString('ru-RU')}</small></span></button>)}
  </section>}
  {lead&&draft&&<div className="drawerBackdrop" onClick={close}><section className="detailDrawer" role="dialog" aria-modal="true" aria-label="Карточка клиента" onClick={e=>e.stopPropagation()}><div className="drawerHeader"><div><span className="kicker">КЛИЕНТ</span><h2>{lead.name}</h2></div><button type="button" aria-label="Закрыть" onClick={close}><X/></button></div><a className="phoneLink" href={'tel:'+lead.phone.replace(/[^+\d]/g,'')}><Phone size={17}/>{lead.phone}</a>
  {requestSummary.lines.length>0&&<section className="leadRequestContext" aria-label="Контекст обращения"><span>КОНТЕКСТ ОБРАЩЕНИЯ</span><h3>{requestSummary.title}</h3><div>{requestSummary.lines.map(line=><b key={line}>{line}</b>)}</div><small>Сформировано автоматически из действия клиента. Заметка менеджера ниже остаётся только для ваших комментариев.</small></section>}
  <fieldset className="formGrid editorFieldset" disabled={busy}><label className="controlField"><span>Статус</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as PulseLead['status']})}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label className="controlField"><span>Ответственный</span><select disabled={runtime.enabled&&runtime.member?.role==='manager'} value={draft.manager||''} onChange={e=>setDraft({...draft,manager:e.target.value||null})}><option value="">Не назначен</option>{runtime.snapshot.members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="controlField wide"><span>Следующее действие</span><input value={draft.nextAction} onChange={e=>setDraft({...draft,nextAction:e.target.value})}/></label><label className="controlField wide"><span>Заметка менеджера</span><textarea rows={4} placeholder="Например: клиент просит перезвонить после 18:00" value={draft.comment} onChange={e=>setDraft({...draft,comment:e.target.value})}/></label></fieldset>
  <div className="leadEditorActions">{error&&<p className="errorNotice" role="alert">{error}</p>}<div><small>{dirty?'Есть несохранённые изменения':'Карточка актуальна'}</small><button type="button" className="primaryAction" aria-label="Сохранить карточку" disabled={busy} onClick={()=>void save()}><Save size={16}/>{busy?'Сохраняем…':dirty?'Сохранить изменения':'Готово'}</button></div></div>
  <h3>Почему такой приоритет</h3><div className="signalList">{(lead.scoreReasons||[]).map(r=><div key={r.ruleId}><b>{r.label}</b><small>{r.points>0?'+':''}{r.points}</small></div>)}</div>
  <h3>Задачи</h3>{tasks.filter(t=>t.leadId===lead.id).map(t=><p key={t.id}>{t.title} · {new Date(t.dueAt).toLocaleString('ru-RU')} · {taskStatusName(t.status)}</p>)}
  <ControlJourneyPanel key={lead.id} leadId={lead.id} properties={state.properties}/><InterestPanel sessionId={lead.sessionId} userId={lead.userId} events={events} state={state} onUseNextAction={value=>{if(!busy)setDraft({...draft,nextAction:value})}}/>
  </section></div>}
 </PageFrame>;
}
