import { ArrowUpRight, ArrowRight, Clock3, Flame, UserRound, Activity, CheckCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageFrame } from '../components/PageFrame';
import { ActivityFeed } from '../components/ActivityFeed';
import { usePulseEvents, usePulseLeads, usePulseProfiles, usePulseState, usePulseTasks } from '../data';
import { useRuntime } from '../RuntimeShell';
export function OverviewPage(){
 const state=usePulseState(),leads=usePulseLeads(),events=usePulseEvents(),profiles=usePulseProfiles(),tasks=usePulseTasks();const current=useRuntime();
 const open=tasks.filter(t=>t.status!=='done').sort((a,b)=>Date.parse(a.dueAt)-Date.parse(b.dueAt));
 const counts=current.counts;
 const stages=[['new','Новые'],['contacted','Связались'],['qualified','Подбор'],['showing','Показ'],['booking','Бронь'],['deal','Сделка']];
 return <PageFrame eyebrow="ОБЗОР КОМАНДЫ" title="Всё важное — в фокусе" description="Клиенты, обязательства и сигналы интереса в одном рабочем пространстве." action={<Link className="primaryAction" to="/leads">Открыть клиентов <ArrowUpRight size={16}/></Link>}>
  <section className="metrics crmMetrics">
   {[{label:'Клиенты в работе',value:counts.activeLeads,detail:counts.newLeads+' новых обращений',to:'/leads',Icon:UserRound},{label:'Горячий интерес',value:counts.hotProfiles,detail:'Люди, готовые к диалогу',to:'/users?filter=hot',Icon:Flame},{label:'Просроченные задачи',value:counts.overdueTasks,detail:'Требуют внимания команды',to:'/tasks?filter=overdue',Icon:Clock3},{label:'Без ответственного',value:counts.unassignedLeads,detail:'Назначьте менеджера',to:'/leads?filter=unassigned',Icon:CheckCheck}].map(({label,value,detail,to,Icon})=><Link to={to} className="metricLink" key={label}><article><div className="metricHeading"><span>{label}</span><Icon size={17}/></div><strong>{value}<ArrowUpRight size={18}/></strong><small>{detail}</small></article></Link>)}
  </section>
  <section className="panel pipelinePanel"><div className="sectionHeading"><div><span className="kicker">ДВИЖЕНИЕ К СДЕЛКЕ</span><h2>Клиенты по этапам</h2></div><Link to="/leads?view=board">Открыть доску <ArrowRight size={15}/></Link></div><div className="pipelineStages">{stages.map(([status,label],i)=>{const count=counts.leadStages[status as keyof typeof counts.leadStages]||0;return <Link key={status} to={'/leads?status='+status}><span><i style={{background:['#8495b1','#6282e6','#9a79d4','#d8a35c','#e16c78','#43a084'][i]}}/>{label}</span><b>{count}</b><div><i style={{width:Math.max(3,count/Math.max(1,counts.leadsTotal)*100)+'%'}}/></div></Link>})}</div></section>
  <div className="dashboardGrid"><section className="panel priorityPanel"><div className="sectionHeading"><div><span className="kicker">ПРИОРИТЕТНАЯ ОЧЕРЕДЬ</span><h2>Что сделать сейчас</h2></div><span className="countBadge">{counts.openTasks}</span></div>
   {!open.length?<div className="emptyState"><CheckCheck size={28}/><strong>Нет открытых задач</strong><span>Новые задачи появятся после обращений клиентов.</span></div>:<div className="workQueue">{open.slice(0,5).map(task=>{const lead=leads.find(l=>l.id===task.leadId);const late=Date.parse(task.dueAt)<Date.now();return <Link to={lead?'/leads?lead='+lead.id:'/tasks'} key={task.id}><span className={'queueMarker '+(late?'late':'')}><Clock3 size={17}/></span><div><b>{lead?.name||'Клиент'}</b><p>{task.title}</p><small className={late?'overdue':''}>{late?'Просрочено · ':''}{new Date(task.dueAt).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div><ArrowUpRight size={16}/></Link>})}</div>}
   <Link className="panelFooterLink" to="/tasks">Все задачи <ArrowRight size={15}/></Link>
  </section><section className="panel interestPanel"><div className="sectionHeading"><div><span className="kicker">СИГНАЛЫ ИНТЕРЕСА</span><h2>Кто выбирает квартиру</h2></div><Flame size={20}/></div><div className="interestList">{[...profiles].sort((a,b)=>b.score-a.score).slice(0,5).map(p=><Link to={'/users?session='+encodeURIComponent(p.sessionId)} key={p.id}><span className={'scoreBadge '+p.priority}><b>{p.score}</b></span><div><b>{p.city||'Город пока не указан'}</b><small>{state.properties.find(x=>x.id===p.topPropertyId)?.name||p.scoreReasons[0]?.label||'Первые действия'}</small></div><ArrowUpRight size={15}/></Link>)}{!profiles.length&&<div className="emptyState"><UserRound size={26}/><strong>Знакомимся с аудиторией</strong><span>Профили появятся после действий в мини-приложении.</span></div>}</div><Link className="panelFooterLink" to="/users">Все посетители <ArrowRight size={15}/></Link></section></div>
  <section className="panel"><div className="sectionHeading"><div><span className="kicker">ЖИВАЯ ИСТОРИЯ</span><h2>Последние действия клиентов</h2></div><Link to="/analytics">Весь журнал <Activity size={15}/></Link></div><ActivityFeed events={events} state={state} compact/></section>
 </PageFrame>;
}
