import React from 'react';
import type {PulseProperty} from '../../../../packages/pulse-data/model';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './Sheet';
import {LeadSheet} from './LeadSheet';
import './clientPolish.css';
export function FloorplanViewer({property,plan}:{property:PulseProperty;plan:PulseProperty['floorplans'][number]}){
 const [zoom,setZoom]=React.useState(1),[broken,setBroken]=React.useState(false);
 const context={floorplanId:plan.id,rooms:plan.roomLabel,areaFrom:plan.areaFrom,areaTo:plan.areaTo,price:plan.priceFrom===null?null:plan.priceFrom*1e6};
 return <Sheet onOpenChange={()=>setZoom(1)}><SheetTrigger asChild><button className="pulsePlanTrigger" aria-label={'Открыть планировку '+plan.roomLabel}>{plan.imageUrl&&!broken?<img src={plan.imageUrl} alt={'Планировка '+plan.roomLabel} loading="lazy" onError={()=>setBroken(true)}/>:<span>Изображение уточняется</span>}<small>Подробнее о планировке</small></button></SheetTrigger><SheetContent side="right" className="pulsePlanViewer"><SheetHeader><SheetTitle>{property.name} · {plan.roomLabel}{plan.roomLabel==='Студия'?'':' комн.'}</SheetTitle><SheetDescription>{plan.areaFrom===null?'Площадь уточняется':plan.areaFrom+(plan.areaTo&&plan.areaTo!==plan.areaFrom?'–'+plan.areaTo:'')+' м²'} · {plan.priceFrom===null?'Цена уточняется':'от '+plan.priceFrom.toLocaleString('ru-RU')+' млн ₽'}</SheetDescription></SheetHeader>{plan.imageUrl&&!broken?<><div className="pulsePlanTools"><button onClick={()=>setZoom(z=>Math.max(1,z-.5))} disabled={zoom===1} aria-label="Уменьшить планировку">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(3,z+.5))} disabled={zoom===3} aria-label="Увеличить планировку">+</button></div><div className="pulsePlanCanvas" tabIndex={0} aria-label="Планировка с прокруткой"><img src={plan.imageUrl} alt={'Планировка '+plan.roomLabel} style={{width:zoom*100+'%',maxWidth:'none'}} onError={()=>setBroken(true)}/></div></>:<p>Изображение пока не загружено. Менеджер уточнит планировку и наличие.</p>}<LeadSheet title="Интересует эта планировка" project={property.name} propertyId={property.id} source="floorplan" context={context}><button className="pulseClientAction">Интересует эта планировка</button></LeadSheet></SheetContent></Sheet>;
}
