import React from 'react';
import { api, runtime, refreshControl } from '../../../../packages/pulse-data/runtime';
export function TeamSettings(){
 const [draft,setDraft]=React.useState({name:'',email:'',password:'',role:'manager',cities:'',telegramUserId:''});const [busy,setBusy]=React.useState(false);const [message,setMessage]=React.useState('');const [audit,setAudit]=React.useState<any[]>([]);
 const owner=runtime.member?.role==='owner';
 React.useEffect(()=>{if(runtime.enabled)void api('/control/audit').then(x=>setAudit(x.items)).catch(()=>{});},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{await api('/control/members',{method:'POST',body:JSON.stringify({...draft,cities:draft.cities.split(',').map(x=>x.trim()).filter(Boolean),telegramUserId:draft.telegramUserId||null})});setDraft({name:'',email:'',password:'',role:'manager',cities:'',telegramUserId:''});await refreshControl();setMessage('Сотрудник добавлен');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось добавить');}finally{setBusy(false);}};
 const edit=async(id:string,patch:Record<string,unknown>)=>{try{await api('/control/members/'+id,{method:'PATCH',body:JSON.stringify(patch)});await refreshControl();}catch(e){setMessage(e instanceof Error?e.message:'Ошибка сохранения');}};
 if(!runtime.enabled)return <section className="panel"><h2>Команда и доступ</h2><p>Демонстрационный режим. В серверной версии здесь доступны сотрудники, роли и журнал действий.</p></section>;
 return <>
 <section className="panel"><span className="kicker">КОМАНДА</span><h2>Доступ и уведомления</h2><p>Менеджер видит назначенных ему клиентов. Администратор управляет каталогом. Владелец управляет командой. Для уведомлений сотрудник должен сначала открыть вашего бота и нажать «Старт».</p>
 <div className="teamList">{runtime.snapshot.members.map(m=><div key={m.id} className="teamRow"><div><b>{m.name}</b><small>{m.email} · {m.role}</small></div><label className="controlField"><span>Telegram ID</span><input key={m.id+':'+m.telegramUserId} disabled={!owner} defaultValue={m.telegramUserId||''} placeholder="Числовой ID" onBlur={e=>{const value=e.target.value.trim();if(value!==(m.telegramUserId||''))void edit(m.id,{telegramUserId:value||null});}}/></label><button disabled={!owner||m.id===runtime.member?.id} onClick={()=>void edit(m.id,{active:!m.active})}>{m.active?'Отключить':'Включить'}</button></div>)}</div>
 {owner&&<form onSubmit={create}><h3>Добавить сотрудника</h3><div className="formGrid">{([['name','Имя'],['email','Email'],['password','Временный пароль · от 14 символов'],['cities','Города через запятую'],['telegramUserId','Telegram ID']] as const).map(([key,label])=><label className="controlField" key={key}><span>{label}</span><input type={key==='password'?'password':key==='email'?'email':'text'} value={draft[key]} required={['name','email','password'].includes(key)} minLength={key==='password'?14:undefined} autoComplete="off" onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label className="controlField"><span>Роль</span><select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="manager">Менеджер</option><option value="admin">Администратор</option></select></label></div><button className="primaryAction" disabled={busy}>{busy?'Создаём…':'Добавить сотрудника'}</button></form>}{message&&<p role="status">{message}</p>}
 </section>
 <section className="panel"><span className="kicker">ДОСТАВКА</span><h2>Уведомления Telegram</h2>{runtime.snapshot.notifications.length?<div className="timeline">{runtime.snapshot.notifications.map(n=><div key={n.id}><b>{n.topic}</b><span>{n.processedAt?'Доставлено':n.deadAt?'Нужна проверка':n.attempts?'Повторная попытка':'В очереди'} · попыток: {n.attempts}</span>{n.lastError&&<small>{n.lastError}</small>}{n.deadAt&&<button onClick={()=>void api("/control/notifications/"+n.id+"/retry",{method:"POST",body:"{}"}).then(()=>refreshControl()).catch(e=>setMessage(e.message))}>Повторить доставку</button>}</div>)}</div>:<p>Очередь уведомлений пуста.</p>}</section>
 <section className="panel"><span className="kicker">АУДИТ</span><h2>Последние изменения</h2><div className="timeline">{audit.map(a=><div key={a.id}><b>{a.action}</b><span>{a.name||'Сотрудник'}</span><small>{new Date(a.createdAt).toLocaleString('ru-RU')}</small></div>)}</div></section>
 </>;
}
