/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BuildingStatus = "archived" | "draft" | "published";

export type DealStatus = "booking" | "deal" | "interested" | "lost" | "meeting" | "new" | "qualified" | "selection_sent";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LeadPipelineStatus = "booking" | "deal" | "interested" | "lost" | "meeting" | "new" | "qualified" | "selection_sent";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OfferStatus = "archived" | "draft" | "published";

export type PartnerStatus = "active" | "archived" | "negotiating" | "paused" | "prospect";

export type PropertyStatus = "archived" | "draft" | "published";

export type TeamRole = "admin" | "analyst" | "content" | "manager" | "owner";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UnitStatus = "archived" | "available" | "reserved" | "sold" | "unknown";

export type UserRole = "admin" | "user";

export interface AnalyticsEvents {
  createdAt: Generated<Timestamp>;
  eventName: string;
  id: Generated<Int8>;
  leadId: Int8 | null;
  metadata: Generated<Json>;
  propertyId: string | null;
  unitId: Int8 | null;
  visitorId: string | null;
}

export interface Buildings {
  address: string | null;
  createdAt: Generated<Timestamp>;
  delivery: string | null;
  id: Generated<Int8>;
  name: string;
  propertyId: string;
  status: Generated<BuildingStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface ClientProfiles {
  budgetMln: Numeric | null;
  city: string | null;
  createdAt: Generated<Timestamp>;
  deliveryPreference: string | null;
  districts: Generated<string[]>;
  downPaymentMln: Numeric | null;
  id: Generated<Int8>;
  leadId: Int8 | null;
  mortgageProgram: string | null;
  preferences: Generated<Json>;
  purchaseType: string | null;
  rooms: number[] | null;
  updatedAt: Generated<Timestamp>;
}

export interface Deals {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  leadId: Int8;
  lostReason: string | null;
  managerUserId: number | null;
  notes: Generated<string>;
  status: Generated<DealStatus>;
  unitId: Int8 | null;
  updatedAt: Generated<Timestamp>;
}

export interface Developers {
  contactName: string | null;
  cooperationTerms: Generated<string>;
  createdAt: Generated<Timestamp>;
  email: string | null;
  id: Generated<Int8>;
  internalNotes: Generated<string>;
  legalName: string | null;
  name: string;
  partnerStatus: Generated<PartnerStatus>;
  phone: string | null;
  telegram: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Floorplans {
  areaFrom: Numeric | null;
  areaTo: Numeric | null;
  id: Generated<Int8>;
  imageUrl: string | null;
  priceFrom: Numeric | null;
  propertyId: string;
  roomLabel: string;
  sortOrder: Generated<number>;
}

export interface ImportRuns {
  errorLog: Generated<Json>;
  finishedAt: Timestamp | null;
  id: Generated<Int8>;
  rowsFailed: Generated<number>;
  rowsSuccess: Generated<number>;
  rowsTotal: Generated<number>;
  sourceName: string;
  sourceType: string;
  startedAt: Generated<Timestamp>;
  status: Generated<string>;
}

export interface LeadHistory {
  actorUserId: number | null;
  createdAt: Generated<Timestamp>;
  eventType: string;
  fromStatus: string | null;
  id: Generated<Int8>;
  leadId: Int8;
  note: string | null;
  toStatus: string | null;
}

export interface Leads {
  borrowerAge: number | null;
  budgetMln: Numeric | null;
  childrenProfile: string | null;
  citizenshipRf: boolean | null;
  comment: string | null;
  createdAt: Generated<Timestamp>;
  downPaymentMln: Numeric | null;
  dvSpecialStatus: string | null;
  id: Generated<Int8>;
  managerUserId: number | null;
  maritalStatus: string | null;
  mortgagePrograms: Generated<string[]>;
  name: string;
  phone: string;
  pipelineStatus: Generated<LeadPipelineStatus>;
  priorPreferentialMortgage: string | null;
  propertyId: string | null;
  purchaseType: string | null;
  qualificationLabel: string | null;
  qualificationNote: string | null;
  source: Generated<string>;
  spouseAge: number | null;
  status: Generated<string>;
  telegram: string | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Matches {
  clientProfileId: Int8;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  reasons: Generated<Json>;
  score: number;
  status: Generated<string>;
  unitId: Int8;
}

export interface Offers {
  benefitText: string | null;
  buildingId: Int8 | null;
  city: string | null;
  conditions: Generated<string>;
  createdAt: Generated<Timestamp>;
  endsAt: Timestamp | null;
  id: Generated<Int8>;
  isPublic: Generated<boolean>;
  isPulseExclusive: Generated<boolean>;
  offerType: string;
  priority: Generated<number>;
  propertyId: string | null;
  startsAt: Timestamp | null;
  status: Generated<OfferStatus>;
  title: string;
  unitId: Int8 | null;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
}

export interface PromoBanners {
  actionUrl: string | null;
  audience: Generated<string>;
  body: Generated<string>;
  city: string | null;
  createdAt: Generated<Timestamp>;
  ctaLabel: string | null;
  endsAt: Timestamp | null;
  id: Generated<Int8>;
  imageUrl: string | null;
  isActive: Generated<boolean>;
  sortOrder: Generated<number>;
  startsAt: Timestamp | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Properties {
  address: string | null;
  city: string;
  className: string;
  coverImageUrl: string | null;
  createdAt: Generated<Timestamp>;
  delivery: string;
  description: Generated<string>;
  developerId: Int8 | null;
  developerName: Generated<string>;
  district: string;
  id: string;
  latitude: number | null;
  longitude: number | null;
  name: string;
  priceFrom: Numeric;
  sortOrder: Generated<number>;
  status: Generated<PropertyStatus>;
  tags: Generated<string[]>;
  updatedAt: Generated<Timestamp>;
}

export interface PropertyFeatures {
  icon: Generated<string>;
  id: Generated<Int8>;
  label: string;
  propertyId: string;
  sortOrder: Generated<number>;
}

export interface PropertyImages {
  alt: Generated<string>;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  propertyId: string;
  sortOrder: Generated<number>;
  url: string;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Units {
  area: Numeric | null;
  buildingId: Int8 | null;
  createdAt: Generated<Timestamp>;
  dataSource: Generated<string>;
  finish: string | null;
  floor: number | null;
  floorsTotal: number | null;
  id: Generated<Int8>;
  layoutUrl: string | null;
  price: Numeric | null;
  pricePerSqm: Numeric | null;
  propertyId: string;
  rooms: number | null;
  sourceUpdatedAt: Timestamp | null;
  status: Generated<UnitStatus>;
  unitNumber: string | null;
  unitType: Generated<string>;
  updatedAt: Generated<Timestamp>;
  viewDescription: string | null;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  teamRole: TeamRole | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  analyticsEvents: AnalyticsEvents;
  buildings: Buildings;
  clientProfiles: ClientProfiles;
  deals: Deals;
  developers: Developers;
  floorplans: Floorplans;
  importRuns: ImportRuns;
  leadHistory: LeadHistory;
  leads: Leads;
  loginAttempts: LoginAttempts;
  matches: Matches;
  offers: Offers;
  promoBanners: PromoBanners;
  properties: Properties;
  propertyFeatures: PropertyFeatures;
  propertyImages: PropertyImages;
  sessions: Sessions;
  units: Units;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const PropertyStatusArrayValues: [PropertyStatus, ...PropertyStatus[]] = ["archived","draft","published"];
export const PartnerStatusArrayValues: [PartnerStatus, ...PartnerStatus[]] = ["active","archived","negotiating","paused","prospect"];
export const BuildingStatusArrayValues: [BuildingStatus, ...BuildingStatus[]] = ["archived","draft","published"];
export const UnitStatusArrayValues: [UnitStatus, ...UnitStatus[]] = ["archived","available","reserved","sold","unknown"];
export const OfferStatusArrayValues: [OfferStatus, ...OfferStatus[]] = ["archived","draft","published"];
export const LeadPipelineStatusArrayValues: [LeadPipelineStatus, ...LeadPipelineStatus[]] = ["booking","deal","interested","lost","meeting","new","qualified","selection_sent"];
export const DealStatusArrayValues: [DealStatus, ...DealStatus[]] = ["booking","deal","interested","lost","meeting","new","qualified","selection_sent"];
export const TeamRoleArrayValues: [TeamRole, ...TeamRole[]] = ["admin","analyst","content","manager","owner"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.